title: Alejandro Elenes
description: Energy systems researcher and engineer.

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

  - scope:
      path: ""
      type: notes
    values:
      layout: note

collections:
  notes:
    output: true
    permalink: /notes/:name/
